language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: B+VlPjot5bA6SRx/gOQWg6TNGWLJ/LYx9Nwsr5CzxiWL2zaLnLxjvMsyQHaoSFrSid+DVnaum5VSWLClxCOSd9J5EQznNNBcTg4X59K+Q4dv2v2FAdhq8hF5shreLbM28wNytNwhWNioIO/Bk/UHLooC0wcBbxGb1joBVnEA07cdBPXreyltu0ZLFcWrKId6sscmeyv3mz/JNGyFzWhWE3kwJsuhB+J1ibD+hCpkPPtGzdQhjDl/zZLTXdSGGEJEWIl8mTddDDEc8jT9GoBJmlmhiNm/DBiBewPXQhvJYiQRi88vjCe8ZA9VvhNqbD22lVX/EbFq1O7FHHqVFMlBPcMUAUuhiIEWs4/P3JFOHFtCGAgKUFx+opBynC/R+o2iZ8MlTKQASsDrES2Wo3OQ35u4DlX/+NzzjteL8WigqPPVBg6WE1HYZrO6n06PZnBo1eLloQH4auG+t4xIwvGCAmzVF2gwyRY0Y7XR038oRAKsxqET8qABLlxcEf/GEOlode+r2Th9V6c7TR+ATAdISS9SdoQMfZbD4zcI5/FTflh+sYsk1nfaVy9pg4cV5SHS32iW4zVpUagaP5VatwP9kj5Ur0/URH2Bdty6Rk02mxMZr9zyrIRuDtivJK9ju3iRtfhxYTBzlA9l6dqbXleIV8J8dQDcfHibSn4TFRzSQ3Q=
  - secure: BqY6ThpM1zQfT79It7gs81asxdLsVnXSiEW6KFR5S9lQuUQy5irXnrFOvWUcS/DmJGwWIjOeJxY5GXDO4F4RCCX73aUR0gklefkhLuRaCX/3C/AptZKeakagGkQ7wHL6SxLgaWhQJITGfH3kXHt594HMGoo8rNtF7nP6TYLvjlsJEHjaGF8/fycCHh7gFhtti2nM4HoOqfApRt2CS/EmeABetQ72VZTTy8bj/56FSlmBV0uEzpGgspm9fTMjVVtTISpvSTK0dBOOtfiCM46SmnQr5P3O9QmeXYrXwm7dMBm7xq1uzcI9rgZPMMArT+rwQerZt6qrJOq/8pnzUJ3NkC+ElMgpj2KfwKPSpgOnW8TuuyZRI0fGFVNgHjgKfSolWIMO1+nWfhtlo8HD/zdTm5GTZsChsH+HqbCREzlVlfNREo+lsGV7sYwd1Gnf3QpuqUncQ/V2LeGv8BKacjZtJ3BsLT40mxtw+tXUIBkvhfrOYqsqONFpFUpmZEB0GgeKYtK6j2+W1v/64amC/SAgDKqy4267ftUw0f+bFXvjbz56PTZiaG+9emHQtUvdaN3dC8A/Psg6fxH+y1JDYhFdY4R2wP7tH51HvKvXlBCelzqn1zn952MPN+izRy6m7UbWgNquCzYyloa8/HNBkzVBlALd8LO5/aFY7BR9uwie2dA=
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
